language: php

branches:
  except:
    - /appveyor.*/

notifications:
  email: false

git:
  depth: 5
  quiet: true

cache:
  timeout: 604800
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.local/opt"
    - "$HOME/.phpunit"
    - "$HOME/bin"

env:
  global:
    - BUILD_PHAR=1
    - BUILD_TYPE=regular
    - BOX_VERSION=3.8.1
    - REPORT_COVERAGE=1
    - ZEPHIR_PARSER_VERSION="v1.3.2"
    - PATH="${HOME}/bin:${PATH}"
    - TRAVIS_COMMIT_LOG="$(git log --format=fuller -5)"
    - MAKEFLAGS="-j $(getconf _NPROCESSORS_ONLN)"
    - SYMFONY_PHPUNIT_DIR="$HOME/.phpunit"

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'

  include:
    - os: linux
      compiler: gcc
      php: '7.0'
      addons:
        apt:
          packages:
            - gdb
      env:
        - BUILD_PHAR=0
        - SYMFONY_PHPUNIT_VERSION=6.5

    - os: linux
      compiler: gcc
      php: '7.1'
      addons:
        apt:
          packages:
            - gdb
      env:
        - SYMFONY_PHPUNIT_VERSION=7.4

    - os: linux
      compiler: gcc
      php: '7.2'
      addons:
        apt:
          packages:
            - gdb
      env:
        - SYMFONY_PHPUNIT_VERSION=7.4

    - os: linux
      compiler: gcc
      php: '7.3'
      addons:
        apt:
          packages:
            - gdb
      env:
        - SYMFONY_PHPUNIT_VERSION=7.4

    - os: linux
      compiler: gcc
      php: '7.4snapshot'
      addons:
        apt:
          packages:
            - gdb
      env:
        # TODO: Recheck
        - BUILD_PHAR=0

    - os: linux
      cache: false
      addons:
        apt:
          packages:
            - shellcheck
      env:
        - BUILD_PHAR=0
        - REPORT_COVERAGE=0
        - BUILD_TYPE=analysis

before_install:
  - |
    # Core dump settings
    ulimit -c unlimited -S || true
    echo '/tmp/core.%e.%p.%t' | sudo tee /proc/sys/kernel/core_pattern

    # To increase the GitHub rate limit we're use GitHub authentication
    if [ -n "$GITHUB_TOKEN" ]; then
      composer config github-oauth.github.com "$GITHUB_TOKEN"
    fi

    # A common path to sore global binaries
    [ -d "$HOME/bin" ] || mkdir "$HOME/bin"

    # Hide "You are in 'detached HEAD' state" message
    git config --global advice.detachedHead false

    # Choose a suitable PHP version to build PHAR (we're use PHP 7.2 for deploy)
    if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then
      composer config platform.php 7.0.33
    fi

install:
  - |
    # Install regular dependencies
    if [ "$BUILD_TYPE" == "regular" ]; then
      .ci/install-prereqs.sh
      composer install --no-interaction --no-ansi --no-progress --no-suggest
    fi

  - |
    # Install dependencies needed for static code analysis
    if [ "$BUILD_TYPE" == "analysis" ]; then
      if [ ! -f "$HOME/bin/php-cs-fixer" ]; then
        wget --quiet -O "$HOME/bin/php-cs-fixer" https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
        chmod +x "$HOME/bin/php-cs-fixer"
      fi

      if [ ! -f "$HOME/bin/phpcs" ]; then
        wget --quiet -O "$HOME/bin/phpcs" https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        chmod +x "$HOME/bin/phpcs"
      fi
    fi

  - |
    # Prepare Zephir executable
    if [ "$BUILD_PHAR" -eq 1 ]
    then
      echo "Build Zephit PHAR"
      .ci/build-phar.sh
      sudo ln -s "$(pwd)/zephir.phar" /usr/local/bin/zephir
    else
      echo "Use Zephir from source"
      sudo ln -s "$(pwd)/zephir" /usr/local/bin/zephir
    fi

before_script:
  - cat .ci/travis.ini >> "$(phpenv root)/versions/$(phpenv version-name)/etc/conf.d/travis.ini"
  - cat "$(phpenv root)/versions/$(phpenv version-name)/etc/conf.d/travis.ini"
  - if [ "$BUILD_TYPE" == "regular" ]; then zephir clean; fi
  - if [ "$BUILD_TYPE" == "regular" ]; then zephir fullclean; fi
  - if [ "$BUILD_TYPE" == "regular" ]; then zephir generate; fi
  - if [ "$BUILD_TYPE" == "regular" ]; then zephir stubs; fi
  - if [ "$BUILD_TYPE" == "regular" ]; then zephir api; fi
  - |
    if [ "$BUILD_TYPE" == "regular" ]; then
      # These variables is needed to produce non optimized code and use code coverage
      LDFLAGS="--coverage"
      CFLAGS="-O0 -ggdb -fprofile-arcs -ftest-coverage"
      CXXFLAGS="-O0 -ggdb -fprofile-arcs -ftest-coverage"

      # Export variables in the subshell to not shadow global variables
      ( export LDFLAGS CFLAGS CXXFLAGS; zephir compile ) || false
    fi

script:
  # Unit testing
  - if [ "$BUILD_TYPE" == "regular" ]; then .ci/run-tests.sh; fi

  # Black-box testing
  - if [ "$BUILD_TYPE" == "regular" ]; then ( cd unit-tests/sharness && PHP=$(phpenv which php) make ); fi

  # Static Code Analysis
  - phpenv config-rm xdebug.ini || true
  - if [ "$BUILD_TYPE" == "analysis" ]; then phpcs; fi
  - if [ "$BUILD_TYPE" == "analysis" ]; then php-cs-fixer fix --diff --dry-run -v; fi
  - if [ "$BUILD_TYPE" == "analysis" ]; then shellcheck .ci/*.sh; fi

after_script:
  - re2c --version
  - printf "$TRAVIS_COMMIT_RANGE\n"
  - printf "$TRAVIS_COMMIT_LOG\n"

after_success:
  - '[[ "$REPORT_COVERAGE" -eq 1 ]] && bash <(curl -s https://codecov.io/bash)'

after_failure:
  - echo "$($(phpenv which php) -v)"
  - echo "$($(phpenv which php) -m)"
  - .ci/after-failure.sh

before_deploy:
  - git config --global user.name cicdbot
  - git config --global user.email team@zephir-lang.com

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: zephir.phar
  skip_cleanup: true
  on:
    tags: true
    php: '7.2'
    condition: $BUILD_TYPE = regular
  repo: phalcon/zephir
