language: php
php:
  - 'nightly'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 1

addons:
  apt:
    packages:
      - gdb
      - lcov

matrix:
  fast_finish: true
  allow_failures:
    - php: 'nightly'

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.composer/cache
    - $HOME/.local/opt
    - .phpunit

env:
  global:
    - RE2C_VERSION="1.1.1"
    - ZEPHIR_PARSER_VERSION="v1.3.0"
    - COLLECT_COVERAGE=true
    - BOX_VERSION=3.3.1
    - PATH="${HOME}/bin:${PATH}"
    - SYMFONY_PHPUNIT_VERSION=5.7.27

before_install:
  - |
      # General settings
      set -e
      stty cols 120
      ulimit -c unlimited -S

      # Export build/test environment variables
      export SYMFONY_PHPUNIT_DIR=$(pwd)/.phpunit
      export PHP_VERNUM="$(php-config --vernum)"

      if [ ! -z "${GITHUB_TOKEN}" ]; then
        composer config github-oauth.github.com ${GITHUB_TOKEN}
        printf "Add Github token\n"
      fi

      [ -d ~/bin ] || mkdir ~/bin

      # Turn the detached message off
      git config --global advice.detachedHead false

      # Change core dumps location
      echo '/tmp/core.%e.%p.%t' | sudo tee /proc/sys/kernel/core_pattern
      sysctl kernel.core_pattern

install:
  - .ci/install-prereqs.sh
  - .ci/install-re2c.sh $RE2C_VERSION
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then composer config platform.php 5.6.33; echo "Preparing to deploy"; fi
  - travis_retry composer install $flags
  - if [ "$(php-config --vernum)" -ge "70100" ]; then .ci/build-phar.sh; fi
  - if [ "$(php-config --vernum)" -lt "70100" ]; then ln -s $(pwd)/zephir ${HOME}/bin/zephir; echo "Use source"; fi

before_script:
  - .ci/build-test-ext.sh
  - cat .ci/travis.ini >> $(phpenv root)/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - zephir --ansi
  - .ci/run-tests.sh
  - (cd unit-tests/sharness && make)

after_success:
  - .ci/after-success.sh

after_failure:
  - .ci/after-failure.sh

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      env:
        - CHECK=php-cs-fixer
        - COLLECT_COVERAGE=false
      install:
        - wget --no-clobber -O $HOME/bin/php-cs-fixer https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
      before_script:
        - chmod +x $HOME/bin/php-cs-fixer
      script:
        - php-cs-fixer --diff --dry-run -v fix

    - stage: Static Code Analysis
      php: 7.2
      env:
        - CHECK=PHP_CodeSniffer
        - COLLECT_COVERAGE=false
      install:
        - wget --no-clobber -O $HOME/bin/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      before_script:
        - chmod +x $HOME/bin/phpcs
      script:
        - phpcs

notifications:
  email: false

before_deploy:
  - git config --global user.name cicdbot
  - git config --global user.email team@zephir-lang.com

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: zephir.phar
  skip_cleanup: true
  on:
    tags: true
    php: '7.2'
  repo: phalcon/zephir
