version: 0.10.16-{build}

environment:
    matrix:
        - PHP_MINOR: 7.0
          VC_VERSION: 14
          BUILD_TYPE: Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

        - PHP_MINOR: 7.0
          VC_VERSION: 14
          BUILD_TYPE: nts-Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

        - PHP_MINOR: 7.1
          VC_VERSION: 14
          BUILD_TYPE: Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

        - PHP_MINOR: 7.1
          VC_VERSION: 14
          BUILD_TYPE: nts-Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

        - PHP_MINOR: 7.2
          VC_VERSION: 15
          BUILD_TYPE: Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

        - PHP_MINOR: 7.2
          VC_VERSION: 15
          BUILD_TYPE: nts-Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    PHP_PATH: C:\Projects\php
    PHP_SDK_PATH: C:\Projects\php-sdk
    PHP_DEVPACK: C:\Projects\php-devpack
    TEST_PHP_EXECUTABLE: C:\Projects\php\php.exe
    PHP_SDK_VERSION: 2.0.7
    PACKAGE_PREFIX: test
    EXTENSION_NAME: test
    EXTENSION_FILE: php_test.dll
    NO_INTERACTION: 1
    REPORT_EXIT_STATUS: 1
    COMPOSER_NO_INTERACTION: 1
    PARSER_VERSION: 1.1.2
    PARSER_RELEASE: 290
    ZEPHIRDIR: c:\projects\zephir

matrix:
    fast_finish: true

cache:
    - 'C:\Downloads -> appveyor.yml'
    - 'vendor -> composer.json'
    - 'composer.phar -> composer.json'

clone_depth: 1
clone_folder: c:\projects\zephir

platform:
    - x86
    - x64

branches:
  only:
    - master
    - development
#    - 0.10.x

init:
    - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "development") {$env:APPVEYOR_CACHE_SKIP_SAVE = "true"}

install:
    - git submodule update --init --recursive
    - ps: Import-Module .\unit-tests\ci\appveyor.psm1
    - ps: AppendSessionPath
    - ps: SetupPhpVersionString
    - ps: EnsureRequiredDirectoriesPresent
    - ps: Ensure7ZipIsInstalled
    - ps: InstallSdk
    - ps: InstallPhp
    - ps: InstallPhpDevPack
    - ps: InstallParser
    - ps: TuneUpPhp

build_script:
    - ps: InitializeBuildVars
    - ps: InitializeReleaseVars
    - ps: InstallBuildDependencies
    - '"%VSCOMNTOOLS%\VsDevCmd" %PLATFORM%'
    - '"%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%'
    - '%PHP_SDK_PATH%\bin\phpsdk_setvars'
    - cd %APPVEYOR_BUILD_FOLDER%
    - 'bin\zephir compile -Wnonexistent-function -Wnonexistent-class -Wunused-variable'
    - cd %APPVEYOR_BUILD_FOLDER%\ext
    - nmake 2> compile-errors.log 1> compile.log
    - ps: EnableExtension

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - 'php unit-tests/phpunit -c phpunit.xml.dist --not-exit --debug unit-tests/'
    - 'php unit-tests/microbench.php'

on_success:
    - ps: PrintBuildDetails

on_failure:
    - ps: PrintLogs
    - ps: PrintVars
    - ps: PrintDirectoriesContent
    - ps: PrintPhpInfo

notifications:
    - provider: Email
      to:
        - build@phalconphp.com
      subject: "Build Zephir [{{status}}]"
      on_build_status_changed: true
