version: 0.12.6-{build}

environment:
    matrix:
        - PHP_MINOR: 7.2
          VC_VERSION: 15
          BUILD_TYPE: nts-Win32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    PHP_PATH: C:\Projects\php
    PHP_SDK_PATH: C:\Projects\php-sdk
    PHP_DEVPACK: C:\Projects\php-devpack
    TEST_PHP_EXECUTABLE: C:\Projects\php\php.exe
    PHP_SDK_VERSION: 2.0.7
    PACKAGE_PREFIX: test
    EXTENSION_NAME: test
    EXTENSION_FILE: php_test.dll
    NO_INTERACTION: 1
    REPORT_EXIT_STATUS: 1
    COMPOSER_NO_INTERACTION: 1
    PARSER_VERSION: 1.3.0
    PARSER_RELEASE: 476
    PSR_VERSION: 0.6.1

matrix:
    fast_finish: true

cache:
    - 'C:\Downloads -> appveyor.yml'
    - 'vendor -> composer.json'
    - '.phpunit'
    - 'composer.phar -> composer.json'
    - '%LOCALAPPDATA%\Composer\files'

clone_depth: 1
clone_folder: c:\projects\zephir

platform:
    - x86
    - x64

branches:
  only:
    - master
    - development

init:
    - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "development") {$env:APPVEYOR_CACHE_SKIP_SAVE = "true"}

install:
    - ps: Import-Module .\.ci\appveyor.psm1
    - ps: AppendSessionPath
    - ps: SetupPhpVersionString
    - ps: EnsureRequiredDirectoriesPresent
    - ps: Ensure7ZipIsInstalled
    - ps: InstallSdk
    - ps: InstallPhp
    - ps: InstallPhpDevPack
    - ps: InstallParser
    - ps: InstallPsrExtension
    - ps: TuneUpPhp

build_script:
    - ps: InitializeBuildVars
    - ps: InitializeReleaseVars
    - ps: InstallBuildDependencies
    - '"%VSCOMNTOOLS%\VsDevCmd" %PLATFORM%'
    - '"%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%'
    - '%PHP_SDK_PATH%\bin\phpsdk_setvars'
    - cd %APPVEYOR_BUILD_FOLDER%
    - zephir compile -Wnonexistent-function -Wnonexistent-class -Wunused-variable -Wnonexistent-constant -Wunreachable-code -Wnot-supported-magic-constant -Wnon-valid-decrement
    - cd %APPVEYOR_BUILD_FOLDER%\ext
    - nmake 2> compile-errors.log 1> compile.log
    - ps: EnableExtension

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - SET X=0
    - php phpunit install
    - php phpunit --bootstrap %APPVEYOR_BUILD_FOLDER%\unit-tests\ext-bootstrap.php --testsuite Extension_Php72 || SET X=!errorlevel!
    - php phpunit --testsuite Zephir || SET X=!errorlevel!
    - exit %X%

on_success:
    - ps: PrintBuildDetails

on_failure:
    - ps: PrintLogs
    - ps: PrintVars
    - ps: PrintDirectoriesContent
    - ps: PrintPhpInfo
