imports:
  - { resource: 'services.yml' }

parameters:
  prototypes_path: "%kernel.project_dir%/prototypes"
  optimizers_path: "%kernel.project_dir%/Library/Optimizers"
  kernels_path: "%kernel.project_dir%/kernels"
  templates_path: "%kernel.project_dir%/templates"
  local_cache_path: "%kernel.local_cache_dir%"

monolog:
  handlers:
    console_stderr:
      type: stream
      path: 'php://stderr'
      process_psr_3_messages: true
      bubble: false
      level: WARNING
      formatter: compiler_log_formatter
    console_stdout:
      type: stream
      path: 'php://stdout'
      process_psr_3_messages: true
      bubble: false
      level: INFO
      formatter: compiler_log_formatter

oneup_flysystem:
  adapters:
    compiler_adapter:
      local:
        directory: "%local_cache_path%"
  filesystems:
    compiler_local:
      adapter: compiler_adapter
      alias: compiler_filesystem
      visibility: public
