services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: monolog.logger, channel: zephir }

  Zephir\:
    resource: '..'
    exclude: '../{autoload.php,bootstrap.php,functions.php}'

  Zephir\Console\Application:
    public: true

  Zephir\FileSystem\FileSystemInterface:
    class: Zephir\FileSystem\HardDisk
    public: true
    lazy: true
    arguments:
      $basePath: '%local_cache_path%'

  Zephir\Config:
    factory: 'Zephir\Config::fromServer'
    class: Zephir\Config
    public: true

  Zephir\Backends\BackendFactory:
    public: true
    arguments:
      $kernelsPath: '%kernels_path%'
      $templatesPath: '%templates_path%'

  Zephir\BaseBackend:
    factory: ['@Zephir\Backends\BackendFactory', 'createBackend']
    public: true

  Zephir\Compiler:
    public: true
    calls:
      - method: setPrototypesPath
        arguments:
          - '%prototypes_path%'
      - method: setOptimizersPath
        arguments:
          - '%optimizers_path%'
      - method: setTemplatesPath
        arguments:
          - '%templates_path%'
      - method: setLogger
        arguments:
          - '@monolog.logger'

  compiler_log_formatter:
    class: Zephir\Logger\Formatter\CompilerFormatter
