name: Linux CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: "Linux: PHP v${{ matrix.php }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php:
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'

        include:
          - php: '7.0'
            symfony_phpunit: '6.5'

          - php: '7.1'
            symfony_phpunit: '7.4'

          - php: '7.2'
            symfony_phpunit: '7.4'

          - php: '7.3'
            symfony_phpunit: '7.4'

          - php: '7.4'
            symfony_phpunit: '7.4'

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, pdo_sqlite, psr, zip
          tools: phpize, php-config
          coverage: xdebug
          # variables_order: https://github.com/phalcon/zephir/pull/1537
          # enable_dl: https://github.com/phalcon/zephir/pull/1654
          # allow_url_fopen: https://github.com/phalcon/zephir/issues/1713
          # error_reporting: https://github.com/zendframework/zend-code/issues/160
          ini-values: variables_order=EGPCS, enable_dl=On, allow_url_fopen=On, error_reporting=-1, memory_limit=1G, date.timezone=UTC, xdebug.max_nesting_level=256

      - name: Set environment variables
        run: |
          echo "::set-env name=SYMFONY_PHPUNIT_VERSION::${{ matrix.symfony_phpunit }}"
          echo "::set-env name=ZEPHIR_PARSER_VERSION::v1.3.3"
          echo "::set-env name=PHP_INI_DIR::$(php-config --configure-options | tr -s " " "\012" | grep with-config-file-scan-dir | cut -d= -f2)"

      - name: Checkout code
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 5

      - name: Common settings
        run: |
          # Core dump settings
          ulimit -c unlimited -S || true

          # Hide "You are in 'detached HEAD' state" message
          git config --global advice.detachedHead false

          # Will be used before as a cache key
          export CPUHASH="$(cat /proc/cpuinfo | grep "model name" | head -n 1 | cut -d':' -f2 | md5sum)"

      - name: Setup APT repositories
        run: |
          # We don't need this at all, and our
          # builds often fails because Microsoft
          # servers are unstable or even offline.
          sudo rm -f /etc/apt/sources.list.d/dotnetdev.list
          sudo rm -f /etc/apt/sources.list.d/azure*.list

      - name: Install system dependencies
        run: |
          sudo apt-get update --quiet --yes 1>/dev/null
          sudo apt-get install --no-install-recommends -q -y re2c

      - name: Get Zephir Parser Cache Key
        id: zephir-parser-cache-key
        run: echo "::set-output name=key::$(echo -n ${ZEPHIR_PARSER_VERSION}_${CPUHASH})"

      - name: Cache Zephir Parser
        uses: actions/cache@v1
        with:
          path: ~/php-zephir-parser
          key: ${{ runner.os }}-${{ matrix.php }}-zephir-parser-${{ steps.zephir-parser-cache.outputs.key }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-zephir-parser-

      - name: Install Zephir Parser
        run: |
          if [ ! -f "$HOME/php-zephir-parser/LICENSE" ]; then
            rm -rf ~/php-zephir-parser
            git clone -b "$ZEPHIR_PARSER_VERSION" \
              --depth 1 \
              -q https://github.com/phalcon/php-zephir-parser \
              "$HOME/php-zephir-parser"
          fi

          cd "$HOME/php-zephir-parser"
          phpize
          ./configure --with-php-config=/usr/bin/php-config --enable-zephir_parser
          make -j"$(getconf _NPROCESSORS_ONLN)"
          sudo make install
          echo 'extension="zephir_parser.so"' | sudo tee "/etc/php/${{ matrix.php }}/cli/conf.d/zephir_parser.ini"

      - name: Setup GitHub Token
        run: |
          # To increase the GitHub rate limit we're use GitHub authentication
          if [ -n "${{ secrets.GH_TOKEN }}" ]; then
            composer config github-oauth.github.com "${{ secrets.GH_TOKEN }}"
          fi

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install project dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

      - name: Prepare Zephir executable
        run: sudo ln -s "$(pwd)/zephir" /usr/local/bin/zephir

      - name: Fast Commands Test
        run: |
          zephir --help
          zephir clean
          zephir fullclean
          zephir generate
          zephir stubs
          zephir api

      - name: Compile Test Project
        run: |
          # These variables are needed to produce non optimized code as well as for code coverage
          LDFLAGS="--coverage"
          CFLAGS="-O0 -ggdb -fprofile-arcs -ftest-coverage"
          CXXFLAGS="-O0 -ggdb -fprofile-arcs -ftest-coverage"

          # Export variables in the subshell to not shadow global variables
          ( export LDFLAGS CFLAGS CXXFLAGS; zephir compile ) || false

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Unit testing
        run: .ci/run-tests.sh

      - name: Black-box testing
        if: always()
        run: cd unit-tests/sharness && PHP=$(which php) make

      - name: After Failure
        if: failure()
        run: .ci/after-failure.sh

      - name: Upload code coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./.codecov.yml
          name: codecov-umbrella
          flags: unittests
          fail_ci_if_error: false

      - name: Success reporting
        if: success()
        run: git log --format=fuller -5
