name: Upload Release Asset

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Environment Variables
        uses: allenevans/set-env@v2.0.0
        with:
          BOX_VERSION: '3.8.4'

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=1G, phar.readonly=0

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo ::set-output name=dir::$(composer config cache-files-dir)

      - name: Setup Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup GitHub Token
        run: |
          # To increase the GitHub rate limit we're use GitHub authentication
          if [ ! -z '${{ secrets.COMPOSER_TOKEN }}' ]; then
            composer config github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}
          fi

      - name: Install Project Dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

      - name: Install Box
        run: |
          wget \
            "https://github.com/humbug/box/releases/download/${BOX_VERSION}/box.phar" \
            --quiet \
            -O ./box

          chmod +x ./box
          sudo mv ./box /usr/local/bin

      - name: Build Zephir PHAR
        run: .ci/build-phar.sh

      - name: Geting Tag Name
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          # This token is provided by GitHub Actions.
          # You DO NOT need to create your own token.
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
          body: 'All notable changes to this version has been documented in the CHANGELOG.md file.'
          # This will update existing tags if any
          allowUpdates: true
          artifacts: zephir.phar
          artifactContentType: application/x-php
